<a href="https://colab.research.google.com/github/vermaayush680/Trust-Link/blob/main/TransUnion%20Data%20Cleaned.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction

The business problem is to create an intelligent automated machine that is capable of classifying credit scores of the users based on the data given!

1. I went through the dataset thoroughly on Excel and found that most of the data is repeated 8 times. The reason for this is that the dataset contains data of users for 8 months Jan to Feb.

2. In these 8 months, many features such as **Age**,**Name**,**Annual Income** etc remained the same while some features are continous and have varying values for the same customer.

Based on the above points , the below work has been done!!!

#Unzipping Dataset

In [1]:
!unzip '/content/fd752804e24411ec.zip'

#Importing Necessary Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

pd. set_option("display.max_rows", None)

#Loading the Training Data

In [3]:
df = pd.read_csv('/content/dataset/train.csv',low_memory=False)

In [4]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

#Data Cleaning

In [6]:
df.isnull().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

## Finding % of Null Data

In [7]:
total_null = df.isnull().sum().sum()
total = np.product(df.shape)

percent_null = total_null / total * 100

print(f"Total Percentage Null Data : {percent_null}")

Total Percentage Null Data : 2.1453928571428573

Our dataset has Months from January to August for each customer.
So instead of dropping the data, I will be filling it.

In [8]:
df.nunique()

ID                          100000
Customer_ID                  12500
Month                            8
Name                         10139
Age                           1788
SSN                          12501
Occupation                      16
Annual_Income                18940
Monthly_Inhand_Salary        13235
Num_Bank_Accounts              943
Num_Credit_Card               1179
Interest_Rate                 1750
Num_of_Loan                    434
Type_of_Loan                  6260
Delay_from_due_date             73
Num_of_Delayed_Payment         749
Changed_Credit_Limit          4384
Num_Credit_Inquiries          1223
Credit_Mix                       4
Outstanding_Debt             13178
Credit_Utilization_Ratio    100000
Credit_History_Age             404
Payment_of_Min_Amount            3
Total_EMI_per_month          14950
Amount_invested_monthly      91049
Payment_Behaviour                7
Monthly_Balance              98792
Credit_Score                     3
dtype: int64

We have 8 repeated months and this is what we'll use for most column filling as most of the data is repaating for a customer

## Name Column Filling

In [9]:
df['Name'].isnull().sum()

9985

In [10]:
def fillnull(data=df,col=None):
  for i in range(data.shape[0]):
    if type(data.loc[i,col]) != str:
      if data.loc[i,'Month'] != 'August':
        j=i+1
        while(type(data.loc[j,col]) != str):
          j+=1
        data.loc[i,col]=data.loc[j,col]
      else:
        data.loc[i,col]=data.loc[i-1,col]
  return data

In [11]:
df = fillnull(data=df,col='Name')

In [12]:
df['Name'].isnull().sum()

0

## Monthly Inhand Salary Column Filling

In [13]:
for i in range(10):
  print(df.loc[i,'Name'],df.loc[i,'Monthly_Inhand_Salary'],type(df.loc[i,'Monthly_Inhand_Salary']))

Aaron Maashoh 1824.8433333333328 <class 'numpy.float64'>
Aaron Maashoh nan <class 'numpy.float64'>
Aaron Maashoh nan <class 'numpy.float64'>
Aaron Maashoh nan <class 'numpy.float64'>
Aaron Maashoh 1824.8433333333328 <class 'numpy.float64'>
Aaron Maashoh nan <class 'numpy.float64'>
Aaron Maashoh 1824.8433333333328 <class 'numpy.float64'>
Aaron Maashoh 1824.8433333333328 <class 'numpy.float64'>
Rick Rothackerj 3037.986666666666 <class 'numpy.float64'>
Rick Rothackerj 3037.986666666666 <class 'numpy.float64'>

In [14]:
df['Monthly_Inhand_Salary']=df['Monthly_Inhand_Salary'].fillna("NAN")

Filling with a random value for easier filtering

<a name="main"></a>

### Function to fill Values

In [15]:
def fillvalues(data=None,col=None):
  data[col] = data[col].fillna('NAN')
  for i in range(data.shape[0]):
    if data.loc[i,col] == 'NAN':
      j=i+1
      if data.loc[i,'Customer_ID'] == data.loc[j,'Customer_ID']:
        while(data.loc[j,col] == 'NAN'):
          j+=1
        data.loc[i,col]=data.loc[j,col]

  for i in range(data.shape[0]):
    if data.loc[i,col] == 'NAN':
      j=i-1
      if data.loc[i,'Customer_ID'] == data.loc[j,'Customer_ID']:
        data.loc[i,col]=data.loc[j,col]
  return data

In [16]:
df = fillvalues(data=df,col='Monthly_Inhand_Salary')

In [17]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [18]:
df[df['Monthly_Inhand_Salary'] == "NAN"]

Empty DataFrame
Columns: [ID, Customer_ID, Month, Name, Age, SSN, Occupation, Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card, Interest_Rate, Num_of_Loan, Type_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment, Changed_Credit_Limit, Num_Credit_Inquiries, Credit_Mix, Outstanding_Debt, Credit_Utilization_Ratio, Credit_History_Age, Payment_of_Min_Amount, Total_EMI_per_month, Amount_invested_monthly, Payment_Behaviour, Monthly_Balance, Credit_Score]
Index: []

[0 rows x 28 columns]

In [19]:
df.to_csv('train2.csv')

## Type Of Loan Column Filling

In [20]:
df.isnull().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                            0
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary           0
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

In [21]:
df[df['Type_of_Loan'].isnull()][['Name','Month','Type_of_Loan']]

                           Name     Month Type_of_Loan
32                       Deepaa   January          NaN
33                       Deepaa  February          NaN
34                       Deepaa     March          NaN
35                       Deepaa     April          NaN
36                       Deepaa       May          NaN
37                       Deepaa      June          NaN
38                       Deepaa      July          NaN
39                       Deepaa    August          NaN
40                           Np   January          NaN
41                           Np  February          NaN
42                           Np     March          NaN
43                           Np     April          NaN
44                           Np       May          NaN
45                           Np      June          NaN
46                           Np      July          NaN
47                           Np    August          NaN
128                       Parkm   January          NaN
129                       Parkm  February          NaN
130                       Parkm     March          NaN
131                       Parkm     April          NaN
132                       Parkm       May          NaN
133                       Parkm      June          NaN
134                       Parkm      July          NaN
135                       Parkm    August          NaN
144             Laurence Frosty   January          NaN
145             Laurence Frosty  February          NaN
146             Laurence Frosty     March          NaN
147             Laurence Frosty     April          NaN
148             Laurence Frosty       May          NaN
149             Laurence Frosty      June          NaN
150             Laurence Frosty      July          NaN
151             Laurence Frosty    August          NaN
160            Mark Felsenthald   January          NaN
161            Mark Felsenthald  February          NaN
162            Mark Felsenthald     March          NaN
163            Mark Felsenthald     April          NaN
164            Mark Felsenthald       May          NaN
165            Mark Felsenthald      June          NaN
166            Mark Felsenthald      July          NaN
167            Mark Felsenthald    August          NaN
176                       Nickb   January          NaN
177                       Nickb  February          NaN
178                       Nickb     March          NaN
179                       Nickb     April          NaN
180                       Nickb       May          NaN
181                       Nickb      June          NaN
182                       Nickb      July          NaN
183                       Nickb    August          NaN
320                       Nateg   January          NaN
321                       Nateg  February          NaN
322                       Nateg     March          NaN
323                       Nateg     April          NaN
324                       Nateg       May          NaN
325                       Nateg      June          NaN
326                       Nateg      July          NaN
327                       Nateg    August          NaN
352                Olivia Oranr   January          NaN
353                Olivia Oranr  February          NaN
354                Olivia Oranr     March          NaN
355                Olivia Oranr     April          NaN
356                Olivia Oranr       May          NaN
357                Olivia Oranr      June          NaN
358                Olivia Oranr      July          NaN
359                Olivia Oranr    August          NaN
424                         Ekr   January          NaN
425                         Ekr  February          NaN
426                         Ekr     March          NaN
427                         Ekr     April          NaN
428                         Ekr       May          NaN
429                         Ekr      June          NaN
430                         Ekr      July          NaN
431                         Ekr    August          NaN
448                       Mikeh   January          NaN
449                       Mikeh  February          NaN
450                       Mikeh     March          NaN
451                       Mikeh     April          NaN
452                       Mikeh       May          NaN
453                       Mikeh      June          NaN
454                       Mikeh      July          NaN
455                       Mikeh    August          NaN
504                   Michelley   January          NaN
505                   Michelley  February          NaN
506                   Michelley     March          NaN
507                   Michelley     April          NaN
508                   Michelley       May          NaN
509                   Michelley      June          NaN
510                   Michelley      July          NaN
511                   Michelley    August          NaN
608                     Slaterf   January          NaN
609                     Slaterf  February          NaN
610                     Slaterf     March          NaN
611                     Slaterf     April          NaN
612                     Slaterf       May          NaN
613                     Slaterf      June          NaN
614                     Slaterf      July          NaN
615                     Slaterf    August          NaN
712                Fiona Ortizx   January          NaN
713                Fiona Ortizx  February          NaN
714                Fiona Ortizx     March          NaN
715                Fiona Ortizx     April          NaN
716                Fiona Ortizx       May          NaN
717                Fiona Ortizx      June          NaN
718                Fiona Ortizx      July          NaN
719                Fiona Ortizx    August          NaN
720              Taiga Uranakan   January          NaN
721              Taiga Uranakan  February          NaN
722              Taiga Uranakan     March          NaN
723              Taiga Uranakan     April          NaN
724              Taiga Uranakan       May          NaN
725              Taiga Uranakan      June          NaN
726              Taiga Uranakan      July          NaN
727              Taiga Uranakan    August          NaN
728                        Suev   January          NaN
729                        Suev  February          NaN
730                        Suev     March          NaN
731                        Suev     April          NaN
732                        Suev       May          NaN
733                        Suev      June          NaN
734                        Suev      July          NaN
735                        Suev    August          NaN
744                    Stempeln   January          NaN
745                    Stempeln  February          NaN
746                    Stempeln     March          NaN
747                    Stempeln     April          NaN
748                    Stempeln       May          NaN
749                    Stempeln      June          NaN
750                    Stempeln      July          NaN
751                    Stempeln    August          NaN
848                    Ritsukoh   January          NaN
849                    Ritsukoh  February          NaN
850                    Ritsukoh     March          NaN
851                    Ritsukoh     April          NaN
852                    Ritsukoh       May          NaN
853                    Ritsukoh      June          NaN
854                    Ritsukoh      July          NaN
855                    Ritsukoh    August          NaN
864               Matt Falloono   January          NaN
865               Matt Falloono  February          NaN
866               Matt Falloono     March          NaN
867               Matt Falloono     April          NaN
868               Matt Falloono       May          NaN
869               Matt Falloono      June          NaN
870               Matt Falloono      July          NaN
871               Matt Falloono    August          NaN
896                   Aless ray   January          NaN
897                   Aless ray  February          NaN
898                   Aless ray     March          NaN
899                   Aless ray     April          NaN
900                   Aless ray       May          NaN
901                   Aless ray      June          NaN
902                   Aless ray      July          NaN
903                   Aless ray    August          NaN
952                    Marilynj   January          NaN
953                    Marilynj  February          NaN
954                    Marilynj     March          NaN
955                    Marilynj     April          NaN
956                    Marilynj       May          NaN
957                    Marilynj      June          NaN
958                    Marilynj      July          NaN
959                    Marilynj    August          NaN
984               Strupczewskid   January          NaN
985               Strupczewskid  February          NaN
986               Strupczewskid     March          NaN
987               Strupczewskid     April          NaN
988               Strupczewskid       May          NaN
989               Strupczewskid      June          NaN
990               Strupczewskid      July          NaN
991               Strupczewskid    August          NaN
1136                      Lashx   January          NaN
1137                      Lashx  February          NaN
1138                      Lashx     March          NaN
1139                      Lashx     April          NaN
1140                      Lashx       May          NaN
1141                      Lashx      June          NaN
1142                      Lashx      July          NaN
1143                      Lashx    August          NaN
1168           "John ODonnell"f   January          NaN
1169           "John ODonnell"f  February          NaN
1170           "John ODonnell"f     March          NaN
1171           "John ODonnell"f     April          NaN
1172           "John ODonnell"f       May          NaN
1173           "John ODonnell"f      June          NaN
1174           "John ODonnell"f      July          NaN
1175           "John ODonnell"f    August          NaN
1232              Sinead Carewi   January          NaN
1233              Sinead Carewi  February          NaN
1234              Sinead Carewi     March          NaN
1235              Sinead Carewi     April          NaN
1236              Sinead Carewi       May          NaN
1237              Sinead Carewi      June          NaN
1238              Sinead Carewi      July          NaN
1239              Sinead Carewi    August          NaN
1248                  Mutikanit   January          NaN
1249                  Mutikanit  February          NaN
1250                  Mutikanit     March          NaN
1251                  Mutikanit     April          NaN
1252                  Mutikanit       May          NaN
1253                  Mutikanit      June          NaN
1254                  Mutikanit      July          NaN
1255                  Mutikanit    August          NaN
1464                   Barbashr   January          NaN
1465                   Barbashr  February          NaN
1466                   Barbashr     March          NaN
1467                   Barbashr     April          NaN
1468                   Barbashr       May          NaN
1469                   Barbashr      June          NaN
1470                   Barbashr      July          NaN
1471                   Barbashr    August          NaN
1496                     Cablef   January          NaN
1497                     Cablef  February          NaN
1498                     Cablef     March          NaN
1499                     Cablef     April          NaN
1500                     Cablef       May          NaN
1501                     Cablef      June          NaN
1502                     Cablef      July          NaN
1503                     Cablef    August          NaN
1528                   Shirboni   January          NaN
1529                   Shirboni  February          NaN
1530                   Shirboni     March          NaN
1531                   Shirboni     April          NaN
1532                   Shirboni       May          NaN
1533                   Shirboni      June          NaN
1534                   Shirboni      July          NaN
1535                   Shirboni    August          NaN
1544                   Toonkeld   January          NaN
1545                   Toonkeld  February          NaN
1546                   Toonkeld     March          NaN
1547                   Toonkeld     April          NaN
1548                   Toonkeld       May          NaN
1549                   Toonkeld      June          NaN
1550                   Toonkeld      July          NaN
1551                   Toonkeld    August          NaN
1568                   McCranke   January          NaN
1569                   McCranke  February          NaN
1570                   McCranke     March          NaN
1571                   McCranke     April          NaN
1572                   McCranke       May          NaN
1573                   McCranke      June          NaN
1574                   McCranke      July          NaN
1575                   McCranke    August          NaN
1832                 Joyce Leeo   January          NaN
1833                 Joyce Leeo  February          NaN
1834                 Joyce Leeo     March          NaN
1835                 Joyce Leeo     April          NaN
1836                 Joyce Leeo       May          NaN
1837                 Joyce Leeo      June          NaN
1838                 Joyce Leeo      July          NaN
1839                 Joyce Leeo    August          NaN
1936                  Mariannae   January          NaN
1937                  Mariannae  February          NaN
1938                  Mariannae     March          NaN
1939                  Mariannae     April          NaN
1940                  Mariannae       May          NaN
1941                  Mariannae      June          NaN
1942                  Mariannae      July          NaN
1943                  Mariannae    August          NaN
2072                     Alpere   January          NaN
2073                     Alpere  February          NaN
2074                     Alpere     March          NaN
2075                     Alpere     April          NaN
2076                     Alpere       May          NaN
2077                     Alpere      June          NaN
2078                     Alpere      July          NaN
2079                     Alpere    August          NaN
2104                    Lawdert   January          NaN
2105                    Lawdert  February          NaN
2106                    Lawdert     March          NaN
2107                    Lawdert     April          NaN
2108                    Lawdert       May          NaN
2109                    Lawdert      June          NaN
2110                    Lawdert      July          NaN
2111                    Lawdert    August          NaN
2120         Andrea Shalal-Esag   January          NaN
2121         Andrea Shalal-Esag  February          NaN
2122         Andrea Shalal-Esag     March          NaN
2123         Andrea Shalal-Esag     April          NaN
2124         Andrea Shalal-Esag       May          NaN
2125         Andrea Shalal-Esag      June          NaN
2126         Andrea Shalal-Esag      July          NaN
2127         Andrea Shalal-Esag    August          NaN
2400                Euan Rochai   January          NaN
2401                Euan Rochai  February          NaN
2402                Euan Rochai     March          NaN
2403                Euan Rochai     April          NaN
2404                Euan Rochai       May          NaN
2405                Euan Rochai      June          NaN
2406                Euan Rochai      July          NaN
2407                Euan Rochai    August          NaN
2496                     Chuckl   January          NaN
2497                     Chuckl  February          NaN
2498                     Chuckl     March          NaN
2499                     Chuckl     April          NaN
2500                     Chuckl       May          NaN
2501                     Chuckl      June          NaN
2502                     Chuckl      July          NaN
2503                     Chuckl    August          NaN
2528                   Melissaj   January          NaN
2529                   Melissaj  February          NaN
2530                   Melissaj     March          NaN
2531                   Melissaj     April          NaN
2532                   Melissaj       May          NaN
2533                   Melissaj      June          NaN
2534                   Melissaj      July          NaN
2535                   Melissaj    August          NaN
2552                     Henryu   January          NaN
2553                     Henryu  February          NaN
2554                     Henryu     March          NaN
2555                     Henryu     April          NaN
2556                     Henryu       May          NaN
2557                     Henryu      June          NaN
2558                     Henryu      July          NaN
2559                     Henryu    August          NaN
2696            Pedro Nicolacim   January          NaN
2697            Pedro Nicolacim  February          NaN
2698            Pedro Nicolacim     March          NaN
2699            Pedro Nicolacim     April          NaN
2700            Pedro Nicolacim       May          NaN
2701            Pedro Nicolacim      June          NaN
2702            Pedro Nicolacim      July          NaN
2703            Pedro Nicolacim    August          NaN
2744                    Drivera   January          NaN
2745                    Drivera  February          NaN
2746                    Drivera     March          NaN
2747                    Drivera     April          NaN
2748                    Drivera       May          NaN
2749                    Drivera      June          NaN
2750                    Drivera      July          NaN
2751                    Drivera    August          NaN
2768                    Polinaa   January          NaN
2769                    Polinaa  February          NaN
2770                    Polinaa     March          NaN
2771                    Polinaa     April          NaN
2772                    Polinaa       May          NaN
2773                    Polinaa      June          NaN
2774                    Polinaa      July          NaN
2775                    Polinaa    August          NaN
2784                   Edwardsi   January          NaN
2785                   Edwardsi  February          NaN
2786                   Edwardsi     March          NaN
2787                   Edwardsi     April          NaN
2788                   Edwardsi       May          NaN
2789                   Edwardsi      June          NaN
2790                   Edwardsi      July          NaN
2791                   Edwardsi    August          NaN
2792                    Grovert   January          NaN
2793                    Grovert  February          NaN
2794                    Grovert     March          NaN
2795                    Grovert     April          NaN
2796                    Grovert       May          NaN
2797                    Grovert      June          NaN
2798                    Grovert      July          NaN
2799                    Grovert    August          NaN
2824                 Baertleinm   January          NaN
2825                 Baertleinm  February          NaN
2826                 Baertleinm     March          NaN
2827                 Baertleinm     April          NaN
2828                 Baertleinm       May          NaN
2829                 Baertleinm      June          NaN
2830                 Baertleinm      July          NaN
2831                 Baertleinm    August          NaN
2928                    Cremerp   January          NaN
2929                    Cremerp  February          NaN

So specific customers have null values for all the months from Jan to Aug.
So let's fill them with "Not Specified" as no further information is given regarding this column

In [22]:
df['Type_of_Loan'].unique()

array(['Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan',
       'Credit-Builder Loan', 'Auto Loan, Auto Loan, and Not Specified',
       ..., 'Home Equity Loan, Auto Loan, Auto Loan, and Auto Loan',
       'Payday Loan, Student Loan, Mortgage Loan, and Not Specified',
       'Personal Loan, Auto Loan, Mortgage Loan, Student Loan, and Student Loan'],
      dtype=object)

In [23]:
df['Type_of_Loan'] = df['Type_of_Loan'].fillna('Not Specified')

In [24]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                           0
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                   0
Delay_from_due_date            0
Num_of_Delayed_Payment      7002
Changed_Credit_Limit           0
Num_Credit_Inquiries        1965
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age          9030
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly     4479
Payment_Behaviour              0
Monthly_Balance             1200
Credit_Score                   0
dtype: int64

## Number of Delayed Payment Column Filling

In [25]:
df[df['Num_of_Delayed_Payment'].isnull()][:20]

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
30,0x162c,CUS_0xb891,July,Jasond,55,072-31-6145,Entrepreneur,30689.89,2612.490833,2,...,Good,632.46,26.056395,17 Years and 9 Months,No,16.415452,71.28367488286933,Low_spent_Large_value_payments,443.5499567906391,Standard
32,0x1632,CUS_0x1cdb,January,Deepaa,21,615-06-7821,Developer,35547.71_,2853.309167,7,...,Standard,943.86,39.797764,30 Years and 8 Months,Yes,0.000000,276.72539431736266,!@9#%8,288.60552234930395,Standard
33,0x1633,CUS_0x1cdb,February,Deepaa,21,615-06-7821,Developer,35547.71,2853.309167,7,...,Standard,943.86,27.020360,30 Years and 9 Months,NM,0.000000,74.44364104999623,High_spent_Medium_value_payments,460.88727561667037,Standard
70,0x1668,CUS_0x4157,July,Charlie Zhur,24,070-19-1622,Doctor,114838.41,9843.8675,2,...,Good,1377.74,31.767516,21 Years and 10 Months,No,226.892792,215.4682977385688,High_spent_Medium_value_payments,792.0256603398883,Good
95,0x168d,CUS_0xc0ab,August,Soyoungd,33,342-90-2649,Engineer,88640.24,7266.686667,3,...,Good,950.36,30.870799,26 Years and 0 Months,No,135.173371,98.44195128223792,High_spent_Large_value_payments,733.0533444127112,Good
106,0x16a0,CUS_0x6c66,March,Sinead Carews,39,328-33-6328,Manager,8701.545_,519.12875,6,...,Standard,2602.69,36.475914,9 Years and 1 Months,NM,36.548197,45.6509755447516,Low_spent_Large_value_payments,239.71370228386124,Poor
140,0x16d2,CUS_0xfdb,May,Patrickg,46,928-91-4452,Teacher,32284.62,2898.385,6,...,_,1283.37,33.239784,6 Years and 9 Months,Yes,103.037560,154.0197492180297,High_spent_Small_value_payments,292.7811904266044,Standard
142,0x16d4,CUS_0xfdb,July,Patrickg,46,928-91-4452,Teacher,32284.62,2898.385,6,...,Standard,1283.37_,24.205533,6 Years and 11 Months,Yes,103.037560,__10000__,Low_spent_Small_value_payments,85.90209492602362,Standard
148,0x16de,CUS_0x3553,May,Laurence Frosty,26,084-25-3745,Musician,97791.42,7449.469347,6,...,_,107.41,38.649114,27 Years and 6 Months,Yes,629.815653,77.60922833984066,High_spent_Large_value_payments,970.3192716601593,Good
152,0x16e6,CUS_0x4100,January,Reema,31,068-83-4394,Entrepreneur,19300.34,1512.361667,6,...,Bad,2430.21,29.934186,18 Years and 2 Months,Yes,49.572062,79.17641583265376,Low_spent_Small_value_payments,312.48768858956015,Poor
164,0x16f6,CUS_0x132f,May,Mark Felsenthald,41,561-60-9294,Musician,19514.88,1828.24,7,...,Standard,881.4,41.176384,19 Years and 7 Months,No,0.000000,168.34146287619103,Low_spent_Small_value_payments,304.48253712380904,Poor
168,0x16fe,CUS_0xa16e,January,Lee Chyenz,41,905-50-7912,Media_Manager,10183.015,1074.584583,7,...,Bad,1672.43,25.951273,10 Years and 1 Months,Yes,37.588073,14.622739235117402,High_spent_Large_value_payments,295.2476462600903,Poor
172,0x1702,CUS_0xa16e,May,Lee Chyenz,41,905-50-7912,Media_Manager,10183.015,1074.584583,7,...,Bad,1672.43,32.293490,10 Years and 5 Months,Yes,37.588073,65.83126164076859,!@9#%8,294.03912385443914,Poor
194,0x1724,CUS_0xa5f9,March,Rickt,34,189-09-5267,Mechanic,57983.12,4720.926667,9,...,Bad,3532.83,37.810243,12 Years and 4 Months,Yes,200.432613,534.3581783879267,Low_spent_Small_value_payments,27.301874884033168,Poor
201,0x172f,CUS_0x4d43,February,Reijik,48,013-39-0742,_______,20787.69,1999.3075,8,...,Standard,614.6,34.235853,17 Years and 11 Months,No,42.221993,82.62718037237505,Low_spent_Large_value_payments,345.0815769711927,Standard
202,0x1730,CUS_0x4d43,March,Reijik,48,013-39-0742,_______,20787.69,1999.3075,8,...,Standard,614.6,22.802145,NaN,No,42.221993,110.17209563183977,Low_spent_Small_value_payments,337.53666171172796,Standard
209,0x173b,CUS_0xb95f,February,Ashleyk,30,467-13-1148,Writer,34290.12,2697.51,9,...,Standard,2686.81,27.036842,NaN,NM,185.111983,__10000__,Low_spent_Large_value_payments,196.5585016421765,Standard
269,0x1793,CUS_0x4004,June,Carlosj,44,679-26-6464,Writer,58317.0,4664.75,8,...,Standard,98.97,24.665525,13 Years and 6 Months,Yes,149.897199,98.88050778293751,High_spent_Medium_value_payments,467.6972927960543,Standard

In [26]:
df['Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].fillna('NAN')

Filling with random value for easier filtering

In [27]:
df = fillvalues(data=df,col='Num_of_Delayed_Payment')

Using that same function from the Monthly Inhand Salary Filling!!

[Click Here to go to the function](#main)

In [28]:
df[df['Num_of_Delayed_Payment'] == 'NAN']

Empty DataFrame
Columns: [ID, Customer_ID, Month, Name, Age, SSN, Occupation, Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card, Interest_Rate, Num_of_Loan, Type_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment, Changed_Credit_Limit, Num_Credit_Inquiries, Credit_Mix, Outstanding_Debt, Credit_Utilization_Ratio, Credit_History_Age, Payment_of_Min_Amount, Total_EMI_per_month, Amount_invested_monthly, Payment_Behaviour, Monthly_Balance, Credit_Score]
Index: []

[0 rows x 28 columns]

In [29]:
df.to_csv('train3.csv')

## Credit History Age Column Filling

In [30]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                           0
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                   0
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit           0
Num_Credit_Inquiries        1965
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age          9030
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly     4479
Payment_Behaviour              0
Monthly_Balance             1200
Credit_Score                   0
dtype: int64

In [31]:
df['Credit_History_Age'].isnull().sum()

9030

In [32]:
df = fillvalues(data=df,col='Credit_History_Age')

Using that same function from the Monthly Inhand Salary Filling!!

[Click Here to go to the function](#main)

In [33]:
df[df['Credit_History_Age']== 'NAN']

Empty DataFrame
Columns: [ID, Customer_ID, Month, Name, Age, SSN, Occupation, Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card, Interest_Rate, Num_of_Loan, Type_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment, Changed_Credit_Limit, Num_Credit_Inquiries, Credit_Mix, Outstanding_Debt, Credit_Utilization_Ratio, Credit_History_Age, Payment_of_Min_Amount, Total_EMI_per_month, Amount_invested_monthly, Payment_Behaviour, Monthly_Balance, Credit_Score]
Index: []

[0 rows x 28 columns]

## Number of Credit Inquiries Column Filling

In [34]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                           0
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                   0
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit           0
Num_Credit_Inquiries        1965
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age             0
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly     4479
Payment_Behaviour              0
Monthly_Balance             1200
Credit_Score                   0
dtype: int64

In [35]:
fillvalues(data=df,col='Num_Credit_Inquiries')

## Amount Invested Monthly Column Filling

In [36]:
df.head(8)[['Annual_Income','Monthly_Inhand_Salary','Interest_Rate','Num_of_Loan','Outstanding_Debt','Payment_of_Min_Amount','Total_EMI_per_month','Amount_invested_monthly','Monthly_Balance']]

,Annual_Income,Monthly_Inhand_Salary,Interest_Rate,Num_of_Loan,Outstanding_Debt,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance
0,19114.12,1824.843333,3,4,809.98,No,49.574949,80.41529543900253,312.49408867943663
1,19114.12,1824.843333,3,4,809.98,No,49.574949,118.28022162236736,284.62916249607184
2,19114.12,1824.843333,3,4,809.98,No,49.574949,81.699521264648,331.2098628537912
3,19114.12,1824.843333,3,4,809.98,No,49.574949,199.4580743910713,223.45130972736786
4,19114.12,1824.843333,3,4,809.98,No,49.574949,41.420153086217326,341.48923103222177
5,19114.12,1824.843333,3,4,809.98,No,49.574949,62.430172331195294,340.4792117872438
6,19114.12,1824.843333,3,4,809.98,No,49.574949,178.3440674122349,244.5653167062043
7,19114.12,1824.843333,3,4,809.98,No,49.574949,24.785216509052056,358.12416760938714

Found some "__10000__" in the data so handling them before filling with mean

In [37]:
df['Amount_invested_monthly'] = df['Amount_invested_monthly'].replace({"__10000__":np.nan})

In [38]:
for i in range(df.shape[0]):
  if pd.isnull(df.loc[i,'Amount_invested_monthly']):
    df.loc[i,'Amount_invested_monthly'] = df[df['Customer_ID'] == df.loc[i,'Customer_ID']]['Amount_invested_monthly'].apply(pd.to_numeric).mean()

I have calculated the mean for each customer and used it to fill the null value.
I could have just calculated the entire column mean but filling of specific customer made more sense!!

## Monthly Balance Column Filling

In [39]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                           0
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                   0
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit           0
Num_Credit_Inquiries           0
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age             0
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly        0
Payment_Behaviour              0
Monthly_Balance             1200
Credit_Score                   0
dtype: int64

In [40]:
for i in range(df.shape[0]):
  if pd.isnull(df.loc[i,'Monthly_Balance']):
    df.loc[i,'Monthly_Balance'] = df[df['Customer_ID'] == df.loc[i,'Customer_ID']]['Monthly_Balance'].apply(pd.to_numeric).mean()

In [41]:
df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

Our Dataset is finally cleaned!!

# Saving the Cleaned Dataset for further processing

In [42]:
df.to_csv('train_cleaned.csv')

In [43]:
from google.colab import files
files.download('/content/train_cleaned.csv')